name: main

on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9, 3.11]
        exclude:
        - os: ubuntu-latest
          python-version: 3.10

    steps:
    #Pobiera zawartość repozytorium.
    - name: Checkout repository
      uses: actions/checkout@v2
    #Ustawia środowisko Python zgodnie z zadeklarowaną wersją.
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    #Aktualizuje narzędzie pip do najnowszej wersji.
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    #Instaluje bibliotekę flake8 do analizy stylu kodu i bibliotekę unittest do testowania.
    - name: Install flake8 and unittest
      run: |
        python -m pip install flake8
        python -m pip install unittest
    #Wyświetla aktualną wersję Pythona.
    - name: Display Python version
      run: python --version
    #Uruchamia analizę stylu kodu przy użyciu flake8.
    - name: Run flake8
      run: |
        flake8
    #Uruchamia testy aplikacji przy użyciu unittest.
    - name: Run unittest
      run: |
        python -m unittest discover -v
